// ============================================================
// 国内远程工作岗位数据
// 数据来源：网络
// 最后更新：2026-03-17
// ============================================================

const JOBS_CN = [
  // ── V2EX 来源（置顶） ──
  {
    id: "cn-020",
    title: "AI 产品工程师",
    company: "（北京初创）",
    logo: "🤖",
    category: "后端开发",
    tags: ["Python", "LLM API", "AI", "北京/远程"],
    salary: "10-15K/月",
    location: "北京/全国远程",
    date: "2026-03-15",
    isNew: true,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "参与 AI 产品研发，使用 Python 和 LLM API 构建智能应用功能模块，与小团队紧密协作。",
    requirements: ["熟练使用 Python", "有 LLM API（OpenAI/Claude/Gemini）集成经验", "对 AI 产品有热情"],
    benefits: ["弹性工时", "初创氛围", "成长空间"]
  },
  {
    id: "cn-021",
    title: "前端工程师（AI 音乐视频平台）",
    company: "（AI 创业公司）",
    logo: "🎵",
    category: "前端开发",
    tags: ["前端", "AI", "音乐", "视频"],
    salary: "15-20K/月",
    location: "全国远程",
    date: "2026-03-14",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责 AI 音乐视频平台的前端研发，打造创意交互体验，与设计师和后端紧密协作。",
    requirements: ["熟练掌握主流前端框架（React/Vue）", "有音视频类产品开发经验优先", "关注用户体验"],
    benefits: ["远程全职", "AI 赛道", "创业期权"]
  },
  {
    id: "cn-022",
    title: "全栈工程师（兼职/AI驱动）",
    company: "（AI 工具初创）",
    logo: "⚡",
    category: "全栈开发",
    tags: ["全栈", "AI", "兼职", "灵活"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-12",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "参与 AI 驱动工具产品的全栈开发，灵活远程合作，技术栈不限，重视实际产出能力。",
    requirements: ["全栈开发能力（前后端均可）", "有 AI 工具产品开发经验优先", "可兼职，自驱力强"],
    benefits: ["灵活兼职", "项目分成机会"]
  },
  {
    id: "cn-023",
    title: "杭州/远程 全栈工程师（偏前端）",
    company: "（杭州科技公司）",
    logo: "🌊",
    category: "前端开发",
    tags: ["全栈", "前端", "React", "杭州/远程"],
    salary: "面议",
    location: "杭州/全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责公司核心产品前端研发，偏向全栈方向，可选择杭州办公或全程远程。",
    requirements: ["熟练使用 React 或 Vue", "有 Node.js 基础", "有独立产品开发经验优先"],
    benefits: ["杭州/远程二选一", "弹性工时"]
  },
  {
    id: "cn-024",
    title: "Web3 运营（长期）",
    company: "（Web3 项目方）",
    logo: "⛓️",
    category: "运营",
    tags: ["Web3", "社区运营", "长期", "远程"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责 Web3 项目的社区运营与增长工作，维护国内外社区渠道，推动用户增长。",
    requirements: ["对 Web3/区块链有深入了解", "有 Telegram/Discord 社区运营经验", "可接受 Token 部分薪资"],
    benefits: ["Token 激励", "远程自由", "长期合作"]
  },
  // ── 2026-03-16 ──
  {
    id: "cn-001",
    title: "物流技术运营专员",
    company: "艾吉赛国际物流集团",
    logo: "🚚",
    category: "运营",
    tags: ["MySQL", "Python", "夜班协作", "远程全职"],
    salary: "8-10K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/894",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责跨时区夜班协作，系统维护及数据库维护工作，支持国际物流集团日常运营。",
    requirements: ["熟悉 MySQL、Python", "可接受跨时区夜班工作", "有物流/运营相关经验优先"],
    benefits: ["五险一金"]
  },
  {
    id: "cn-002",
    title: "HR主管",
    company: "（代招·电商行业）",
    logo: "👥",
    category: "人力资源",
    tags: ["HR", "电商", "远程全职"],
    salary: "20-21K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/893",
    sourceUrl: "https://www.zhipin.com/job_detail/b188f87a8320fc2703dz2ti1GVdS.html",
    description: "负责电商公司组织人事全流程，包括员工培训实施、员工关系管理等工作。",
    requirements: ["HR全流程经验", "有电商行业背景优先", "组织培训能力强"],
    benefits: ["绩效奖金"]
  },
  {
    id: "cn-003",
    title: "插画设计师",
    company: "海宁米晗文化传播有限公司",
    logo: "🎨",
    category: "UI/UX设计",
    tags: ["插画", "兼职", "电商设计"],
    salary: "8-12K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/892",
    sourceUrl: "https://www.zhaopin.com/jobdetail/CCL1475319280J40833117707.htm",
    description: "承接电商设计/宣传海报/出版物/包装等插画创作，线上接单，可兼职合作。",
    requirements: ["有插画设计作品集", "熟悉电商视觉规范", "可接受按稿计费"],
    benefits: ["灵活兼职", "作品积累"]
  },
  {
    id: "cn-004",
    title: "商旅客服",
    company: "外企德科",
    logo: "✈️",
    category: "客户服务",
    tags: ["差旅服务", "客服", "远程全职"],
    salary: "8-12K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/891",
    sourceUrl: "#",
    description: "为企业客户提供差旅全流程支持，对接酒店、机票、用车等预订，整理知识库与SOP。",
    requirements: ["有客服/差旅服务经验", "沟通能力强", "有社保"],
    benefits: ["五险一金", "大外企背景"]
  },
  {
    id: "cn-005",
    title: "新媒体运营",
    company: "（留学服务行业）",
    logo: "📱",
    category: "运营",
    tags: ["新媒体", "文案", "留学"],
    salary: "7-8K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/887",
    sourceUrl: "#",
    description: "负责留学服务机构的新媒体内容创作与账号日常运营，包括文案整理、视频剪辑、社群搭建和客户咨询工作。",
    requirements: ["英语读写能力", "有新媒体运营经验", "了解留学行业优先"],
    benefits: ["弹性工时"]
  },
  // ── 2026-03-13 ──
  {
    id: "cn-006",
    title: "GOLANG 后端开发",
    company: "（猎头代招）",
    logo: "⚙️",
    category: "后端开发",
    tags: ["Golang", "微服务", "Kubernetes", "远程全职"],
    salary: "20-40K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: true,
    source: "https://remote-china.com/jobs/884",
    sourceUrl: "https://www.zhipin.com/job_detail/2f8614091104659e0nVz29q_GVNV.html",
    description: "负责可观测平台后端研发，数据采集分析，参与微服务架构设计与优化。",
    requirements: ["Golang 扎实", "熟悉微服务架构", "有 Kubernetes 使用经验", "可观测平台经验优先"],
    benefits: ["猎头推荐", "大厂待遇"]
  },
  {
    id: "cn-007",
    title: "广告投放项目经理",
    company: "珠海翼进顾问咨询有限公司",
    logo: "📊",
    category: "运营",
    tags: ["广告投放", "项目管理", "远程全职"],
    salary: "15-20K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/883",
    sourceUrl: "#",
    description: "负责广告投放项目统筹管理，数据跟进复盘，策略执行优化，覆盖多媒体渠道。",
    requirements: ["有广告投放或项目管理经验", "数据分析能力强", "逻辑思维清晰"],
    benefits: ["绩效奖金", "弹性远程"]
  },
  {
    id: "cn-008",
    title: "招聘专员",
    company: "武汉银禾科技有限公司",
    logo: "🔍",
    category: "人力资源",
    tags: ["招聘", "软件互联网", "远程全职"],
    salary: "14-28K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/882",
    sourceUrl: "https://www.zhipin.com/job_detail/fa94f3e6ad411ddf0nZ42929F1FX.html",
    description: "全流程招聘执行，渠道优化，数据分析，支持软件互联网行业人才获取。",
    requirements: ["有互联网行业招聘经验", "熟悉主流招聘平台", "数据驱动的招聘思维"],
    benefits: ["五险一金", "绩效提成"]
  },
  {
    id: "cn-009",
    title: "思辨老师",
    company: "杭州维学新知网络科技有限公司",
    logo: "📚",
    category: "教育/培训",
    tags: ["小班教学", "小学生", "远程全职"],
    salary: "8-12K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/885",
    sourceUrl: "#",
    description: "面向小学生开展思辨逻辑小班在线教学，培养学生批判思维和表达能力。",
    requirements: ["有小学段教学经验", "表达能力强", "耐心细致"],
    benefits: ["五险（大连参保）", "课时奖励"]
  },
  {
    id: "cn-010",
    title: "线上行政客服",
    company: "济南云旅商贸服务有限公司",
    logo: "💬",
    category: "客户服务",
    tags: ["客服", "电商", "兼职可"],
    salary: "6-8K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/886",
    sourceUrl: "#",
    description: "解答公司产品问题，跟踪客户需求，维护良好客户关系，可全职或兼职。",
    requirements: ["沟通能力强", "打字速度 50+ 字/分钟", "有电商平台经验优先"],
    benefits: ["灵活兼职", "提成奖励"]
  },
  // ── 2026-03-11 ──
  {
    id: "cn-011",
    title: "JAVA 高级架构师",
    company: "上海游昆信息技术有限公司",
    logo: "☕",
    category: "后端开发",
    tags: ["Java", "分布式系统", "广告技术", "远程全职"],
    salary: "30-50K/月",
    location: "全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: true,
    source: "https://remote-china.com/jobs/880",
    sourceUrl: "#",
    description: "负责大数据平台产品的高级架构设计，参与广告技术生态建设，推动分布式系统技术升级。",
    requirements: ["精通 Java 和分布式系统", "熟悉广告技术生态", "有大型平台架构设计经验"],
    benefits: ["高薪", "股票期权", "弹性远程"]
  },
  {
    id: "cn-012",
    title: "全栈工程师（AI Agent）",
    company: "中硅星云科技（广州）有限公司",
    logo: "🤖",
    category: "全栈开发",
    tags: ["Node.js", "Python", "Flutter", "AI Agent", "RAG"],
    salary: "12-24K/月",
    location: "全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/876",
    sourceUrl: "https://www.zhaopin.com/jobdetail/CCL1507259470J40831719411.htm",
    description: "参与 AI Agent 相关产品研发，独立完成前后端功能模块开发，覆盖移动端与 Web。",
    requirements: ["熟练使用 Node.js / Python / Golang", "有 Flutter 开发经验", "了解 RAG 框架优先"],
    benefits: ["弹性工时", "AI 方向成长"]
  },
  {
    id: "cn-013",
    title: "GO 开发工程师",
    company: "深圳漫奢生物科技有限公司",
    logo: "🐹",
    category: "后端开发",
    tags: ["Golang", "Java", "云原生", "To B SaaS"],
    salary: "17-20K/月",
    location: "全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/875",
    sourceUrl: "#",
    description: "外贸行业 To B SaaS 产品后端开发，负责云原生架构迭代与 DevOps 流程建设。",
    requirements: ["熟练掌握 Golang/Java", "了解 DevOps 和云原生技术", "有 To B SaaS 开发经验优先"],
    benefits: ["弹性远程", "绩效奖金"]
  },
  {
    id: "cn-014",
    title: "知识产权专员（英语笔译）",
    company: "北京安杰世泽律师事务所",
    logo: "⚖️",
    category: "法律/知识产权",
    tags: ["知识产权", "英语翻译", "专利", "远程全职"],
    salary: "13-15K/月",
    location: "全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/874",
    sourceUrl: "https://www.zhaopin.com/jobdetail/CCL1436870760J40757721506.htm",
    description: "处理知识产权相关事务及英语笔译工作，服务于知名律师事务所的涉外知产业务。",
    requirements: ["化学工程/高分子材料相关专业", "持有专利代理师资格证", "英语笔译能力强"],
    benefits: ["专业背景积累", "大所平台"]
  },
  // ── 2026-03-10 ──
  {
    id: "cn-015",
    title: "全栈工程师（AI Ads Agent）",
    company: "（广告营销行业初创）",
    logo: "💡",
    category: "全栈开发",
    tags: ["Python", "Node.js", "React", "LLM API", "RAG"],
    salary: "20-30K/月",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: true,
    source: "https://remote-china.com/jobs/866",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责 AI 广告 Agent 产品全栈研发，接入 LLM API 和 RAG 框架，打造智能广告生成工具。",
    requirements: ["熟悉 Python、Node.js、React", "有 LLM API 接入经验", "了解 RAG 框架优先"],
    benefits: ["初创期权", "AI 赛道机会"]
  },
  {
    id: "cn-016",
    title: ".NET 全栈开发（兼职）",
    company: "WooPOS",
    logo: "🛒",
    category: "全栈开发",
    tags: [".NET", "Blazor", "GraphQL", "兼职", "ERP"],
    salary: "50-120元/小时",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/865",
    sourceUrl: "#",
    description: "参与进销存 ERP 系统开发，使用 .NET、Blazor、GraphQL 技术栈，灵活兼职合作。",
    requirements: ["熟练掌握 .NET / Blazor", "了解 GraphQL", "有 ERP 系统开发经验优先"],
    benefits: ["时薪结算", "灵活兼职"]
  },
  {
    id: "cn-017",
    title: "Python 后端开发",
    company: "大连思泰克科技有限公司",
    logo: "🐍",
    category: "后端开发",
    tags: ["Python", "FastAPI", "TypeScript", "英语交流"],
    salary: "14-28K/月",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/864",
    sourceUrl: "#",
    description: "负责软件外包项目的后端开发工作，使用 Python FastAPI，具备基本前端能力，支持英语交流。",
    requirements: ["熟练掌握 Python、FastAPI", "基本前端能力（TypeScript）", "英语交流能力"],
    benefits: ["远程弹性", "外包项目奖金"]
  },
  // ── 2026-03-09 ──
  {
    id: "cn-018",
    title: "谷歌 SEO 专员",
    company: "成都柳暗星河科技有限公司",
    logo: "🔎",
    category: "市场营销",
    tags: ["SEO", "Google", "外链建设", "数据分析"],
    salary: "10-20K/月",
    location: "全国远程",
    date: "2026-03-09",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/856",
    sourceUrl: "#",
    description: "负责谷歌 SEO 优化工作，包括关键词优化、SEO 审计、外链建设及数据分析报告。",
    requirements: ["有 Google SEO 实战经验", "熟悉 SEO 工具（Ahrefs/SEMrush）", "数据分析能力"],
    benefits: ["弹性远程", "绩效提成"]
  },
  {
    id: "cn-019",
    title: "前端/后端工程师",
    company: "（软件外包）",
    logo: "💻",
    category: "前端开发",
    tags: ["Vue", "Java", "Spring", "兼职可"],
    salary: "20-40K/月",
    location: "全国远程",
    date: "2026-03-09",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/854",
    sourceUrl: "#",
    description: "参与软件外包项目开发，前端使用 Vue，后端使用 Java+Spring，可兼职合作。",
    requirements: ["前端：熟练掌握 Vue", "后端：熟练掌握 Java、Spring", "可兼职"],
    benefits: ["可兼职", "灵活合作"]
  }
];
