// ============================================================
// 国内远程工作岗位数据
// 数据来源：远程中文网等
// 最后更新：2026-03-21
// ============================================================

const JOBS_CN = [
  {
    id: 'cn-remotechina-02194',
    title: '法律销售',
    company: '北京国舜（合肥）律师事务所',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '法律服务行业，电话销售，网络销售，案件邀约面谈，案件交接，需要行业经验，12-24k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/916',
    applyUrl: 'https://remote-china.com/jobs/916',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-12626',
    title: '研学项目协调员',
    company: '北京碧山国际旅行社有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '文旅行业，项目跟单，体验式教育项目，英语交流，团队沟通，7-8k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/915',
    applyUrl: 'https://remote-china.com/jobs/915',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-22776',
    title: '餐饮管理客服',
    company: '成都芙铭丽餐饮管理有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '餐饮管理行业，线上客服，售前/售中/售后服务，数据处理分析，6-9k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/914',
    applyUrl: 'https://remote-china.com/jobs/914',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-35269',
    title: '平面设计师',
    company: '河南友美印务有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '印刷行业，平面设计师，名片等排版设计，可日结，CDR, PS, 7-10k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/913',
    applyUrl: 'https://remote-china.com/jobs/913',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-47905',
    title: '职业规划师',
    company: '壹职帮(福州)数智科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '教育培训行业，职业规划师，课程销售，电话销售，有社保，7-12k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/912',
    applyUrl: 'https://remote-china.com/jobs/912',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-53274',
    title: 'AI阅读项目产品经理',
    company: '创而新(北京)科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '教育培训行业，AI阅读项目产品经理，LLM, 互联网/教育类产品经验，9-10k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/911',
    applyUrl: 'https://remote-china.com/jobs/911',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-6879',
    title: '全栈工程师',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: 'AI相关产品，全栈开发工程师，TypeScript, Next.js, Hono, React, L',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/910',
    applyUrl: 'https://remote-china.com/jobs/910',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-74439',
    title: '.NET方向技术总监',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '国际物流行业，技术总监， .NET, C#, 团队/项目/路线图管理，战略规划，英语交流， 15-2',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/909',
    applyUrl: 'https://remote-china.com/jobs/909',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-87001',
    title: '游戏中法翻译',
    company: '甲骨易(北京)语言科技股份有限公司湖南分公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '翻译服务行业，游戏本地化，法语翻译，校对，质量测试，术语整理，10-15k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/908',
    applyUrl: 'https://remote-china.com/jobs/908',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-99695',
    title: '医学专员',
    company: '北京诺和德美医药技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '生物医药行业，医学专员，文献检查汇总，报告撰写，稿件质量控制，需要相关专业，7-10k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/907',
    applyUrl: 'https://remote-china.com/jobs/907',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-109532',
    title: '小红书运营',
    company: '洛阳万乾文化传媒有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '电商行业，新媒体运营，小红书店铺管理，文字策划，数据分析，兼职，8-9k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/906',
    applyUrl: 'https://remote-china.com/jobs/906',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-11709',
    title: '外贸业务员',
    company: '天津汇来国际贸易有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '建材类产品，外贸业务员，市场拓展，客户维护，客户底盘，商务谈判，有社保，8-10k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/905',
    applyUrl: 'https://remote-china.com/jobs/905',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-126091',
    title: 'HR',
    company: '重庆波士科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '软件互联网行业，HR，技术/非技术岗位招聘，招聘全流程，需要大厂或者金融经验，15-27k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/904',
    applyUrl: 'https://remote-china.com/jobs/904',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-135131',
    title: '轻小说作者',
    company: '上海桌桌子信息技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '动漫动画行业，二次元相关，轻小说作者，剧本创作，男女频，9-16k',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/903',
    applyUrl: 'https://remote-china.com/jobs/903',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-142129',
    title: '海外游戏策划',
    company: '奎拔科技(北京)有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: ['远程'],
    salary: '游戏行业，游戏策划，海外游戏，系统设计，关卡编辑，数据高估，Unity Editor, Prefab',
    location: '全国远程',
    date: '2026-03-21',
    isNew: True,
    isFeatured: False,
    canRefer: False,
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/902',
    applyUrl: 'https://remote-china.com/jobs/902',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-02071',
    title: '法律销售',
    company: '北京国舜（合肥）律师事务所',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '法律服务行业，电话销售，网络销售，案件邀约面谈，案件交接，需要行业经验，12-24k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/916',
    applyUrl: 'https://remote-china.com/jobs/916',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-12748',
    title: '研学项目协调员',
    company: '北京碧山国际旅行社有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '文旅行业，项目跟单，体验式教育项目，英语交流，团队沟通，7-8k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/915',
    applyUrl: 'https://remote-china.com/jobs/915',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-22813',
    title: '餐饮管理客服',
    company: '成都芙铭丽餐饮管理有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '餐饮管理行业，线上客服，售前/售中/售后服务，数据处理分析，6-9k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/914',
    applyUrl: 'https://remote-china.com/jobs/914',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-32813',
    title: '平面设计师',
    company: '河南友美印务有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '印刷行业，平面设计师，名片等排版设计，可日结，CDR, PS, 7-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/913',
    applyUrl: 'https://remote-china.com/jobs/913',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-41211',
    title: '职业规划师',
    company: '壹职帮(福州)数智科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '教育培训行业，职业规划师，课程销售，电话销售，有社保，7-12k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/912',
    applyUrl: 'https://remote-china.com/jobs/912',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-5462',
    title: 'AI阅读项目产品经理',
    company: '创而新(北京)科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '教育培训行业，AI阅读项目产品经理，LLM, 互联网/教育类产品经验，9-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/911',
    applyUrl: 'https://remote-china.com/jobs/911',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-69730',
    title: '全栈工程师',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: 'AI相关产品，全栈开发工程师，TypeScript, Next.js, Hono, React, L',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/910',
    applyUrl: 'https://remote-china.com/jobs/910',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-72471',
    title: '.NET方向技术总监',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '国际物流行业，技术总监， .NET, C#, 团队/项目/路线图管理，战略规划，英语交流， 15-2',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/909',
    applyUrl: 'https://remote-china.com/jobs/909',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-84022',
    title: '游戏中法翻译',
    company: '甲骨易(北京)语言科技股份有限公司湖南分公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '翻译服务行业，游戏本地化，法语翻译，校对，质量测试，术语整理，10-15k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/908',
    applyUrl: 'https://remote-china.com/jobs/908',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-91686',
    title: '医学专员',
    company: '北京诺和德美医药技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '生物医药行业，医学专员，文献检查汇总，报告撰写，稿件质量控制，需要相关专业，7-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/907',
    applyUrl: 'https://remote-china.com/jobs/907',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-107859',
    title: '小红书运营',
    company: '洛阳万乾文化传媒有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '电商行业，新媒体运营，小红书店铺管理，文字策划，数据分析，兼职，8-9k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/906',
    applyUrl: 'https://remote-china.com/jobs/906',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-117870',
    title: '外贸业务员',
    company: '天津汇来国际贸易有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '建材类产品，外贸业务员，市场拓展，客户维护，客户底盘，商务谈判，有社保，8-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/905',
    applyUrl: 'https://remote-china.com/jobs/905',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-123674',
    title: 'HR',
    company: '重庆波士科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '软件互联网行业，HR，技术/非技术岗位招聘，招聘全流程，需要大厂或者金融经验，15-27k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/904',
    applyUrl: 'https://remote-china.com/jobs/904',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-137424',
    title: '轻小说作者',
    company: '上海桌桌子信息技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '动漫动画行业，二次元相关，轻小说作者，剧本创作，男女频，9-16k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/903',
    applyUrl: 'https://remote-china.com/jobs/903',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-14531',
    title: '海外游戏策划',
    company: '奎拔科技(北京)有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '游戏行业，游戏策划，海外游戏，系统设计，关卡编辑，数据高估，Unity Editor, Prefab',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/902',
    applyUrl: 'https://remote-china.com/jobs/902',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-05987',
    title: '法律销售',
    company: '北京国舜（合肥）律师事务所',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '法律服务行业，电话销售，网络销售，案件邀约面谈，案件交接，需要行业经验，12-24k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/916',
    applyUrl: 'https://remote-china.com/jobs/916',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-13101',
    title: '研学项目协调员',
    company: '北京碧山国际旅行社有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '文旅行业，项目跟单，体验式教育项目，英语交流，团队沟通，7-8k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/915',
    applyUrl: 'https://remote-china.com/jobs/915',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-25892',
    title: '餐饮管理客服',
    company: '成都芙铭丽餐饮管理有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '餐饮管理行业，线上客服，售前/售中/售后服务，数据处理分析，6-9k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/914',
    applyUrl: 'https://remote-china.com/jobs/914',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-34306',
    title: '平面设计师',
    company: '河南友美印务有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '印刷行业，平面设计师，名片等排版设计，可日结，CDR, PS, 7-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/913',
    applyUrl: 'https://remote-china.com/jobs/913',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-47640',
    title: '职业规划师',
    company: '壹职帮(福州)数智科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '教育培训行业，职业规划师，课程销售，电话销售，有社保，7-12k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/912',
    applyUrl: 'https://remote-china.com/jobs/912',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-55506',
    title: 'AI阅读项目产品经理',
    company: '创而新(北京)科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '教育培训行业，AI阅读项目产品经理，LLM, 互联网/教育类产品经验，9-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/911',
    applyUrl: 'https://remote-china.com/jobs/911',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-67013',
    title: '全栈工程师',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: 'AI相关产品，全栈开发工程师，TypeScript, Next.js, Hono, React, L',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/910',
    applyUrl: 'https://remote-china.com/jobs/910',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-78686',
    title: '.NET方向技术总监',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '国际物流行业，技术总监， .NET, C#, 团队/项目/路线图管理，战略规划，英语交流， 15-2',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/909',
    applyUrl: 'https://remote-china.com/jobs/909',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-82826',
    title: '游戏中法翻译',
    company: '甲骨易(北京)语言科技股份有限公司湖南分公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '翻译服务行业，游戏本地化，法语翻译，校对，质量测试，术语整理，10-15k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/908',
    applyUrl: 'https://remote-china.com/jobs/908',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-93356',
    title: '医学专员',
    company: '北京诺和德美医药技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '生物医药行业，医学专员，文献检查汇总，报告撰写，稿件质量控制，需要相关专业，7-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/907',
    applyUrl: 'https://remote-china.com/jobs/907',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-109083',
    title: '小红书运营',
    company: '洛阳万乾文化传媒有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '电商行业，新媒体运营，小红书店铺管理，文字策划，数据分析，兼职，8-9k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/906',
    applyUrl: 'https://remote-china.com/jobs/906',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-119116',
    title: '外贸业务员',
    company: '天津汇来国际贸易有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '建材类产品，外贸业务员，市场拓展，客户维护，客户底盘，商务谈判，有社保，8-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/905',
    applyUrl: 'https://remote-china.com/jobs/905',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-125069',
    title: 'HR',
    company: '重庆波士科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '软件互联网行业，HR，技术/非技术岗位招聘，招聘全流程，需要大厂或者金融经验，15-27k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/904',
    applyUrl: 'https://remote-china.com/jobs/904',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-135067',
    title: '轻小说作者',
    company: '上海桌桌子信息技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '动漫动画行业，二次元相关，轻小说作者，剧本创作，男女频，9-16k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/903',
    applyUrl: 'https://remote-china.com/jobs/903',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-146078',
    title: '海外游戏策划',
    company: '奎拔科技(北京)有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '游戏行业，游戏策划，海外游戏，系统设计，关卡编辑，数据高估，Unity Editor, Prefab',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/902',
    applyUrl: 'https://remote-china.com/jobs/902',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-0755',
    title: '法律销售',
    company: '北京国舜（合肥）律师事务所',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '法律服务行业，电话销售，网络销售，案件邀约面谈，案件交接，需要行业经验，12-24k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/916',
    applyUrl: 'https://remote-china.com/jobs/916',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-19902',
    title: '研学项目协调员',
    company: '北京碧山国际旅行社有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '文旅行业，项目跟单，体验式教育项目，英语交流，团队沟通，7-8k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/915',
    applyUrl: 'https://remote-china.com/jobs/915',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-24866',
    title: '餐饮管理客服',
    company: '成都芙铭丽餐饮管理有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '餐饮管理行业，线上客服，售前/售中/售后服务，数据处理分析，6-9k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/914',
    applyUrl: 'https://remote-china.com/jobs/914',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-34095',
    title: '平面设计师',
    company: '河南友美印务有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '印刷行业，平面设计师，名片等排版设计，可日结，CDR, PS, 7-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/913',
    applyUrl: 'https://remote-china.com/jobs/913',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-47587',
    title: '职业规划师',
    company: '壹职帮(福州)数智科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '教育培训行业，职业规划师，课程销售，电话销售，有社保，7-12k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/912',
    applyUrl: 'https://remote-china.com/jobs/912',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-59410',
    title: 'AI阅读项目产品经理',
    company: '创而新(北京)科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '教育培训行业，AI阅读项目产品经理，LLM, 互联网/教育类产品经验，9-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/911',
    applyUrl: 'https://remote-china.com/jobs/911',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-68584',
    title: '全栈工程师',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: 'AI相关产品，全栈开发工程师，TypeScript, Next.js, Hono, React, L',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/910',
    applyUrl: 'https://remote-china.com/jobs/910',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-795',
    title: '.NET方向技术总监',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '国际物流行业，技术总监， .NET, C#, 团队/项目/路线图管理，战略规划，英语交流， 15-2',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/909',
    applyUrl: 'https://remote-china.com/jobs/909',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-85615',
    title: '游戏中法翻译',
    company: '甲骨易(北京)语言科技股份有限公司湖南分公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '翻译服务行业，游戏本地化，法语翻译，校对，质量测试，术语整理，10-15k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/908',
    applyUrl: 'https://remote-china.com/jobs/908',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-92209',
    title: '医学专员',
    company: '北京诺和德美医药技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '生物医药行业，医学专员，文献检查汇总，报告撰写，稿件质量控制，需要相关专业，7-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/907',
    applyUrl: 'https://remote-china.com/jobs/907',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-102182',
    title: '小红书运营',
    company: '洛阳万乾文化传媒有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '电商行业，新媒体运营，小红书店铺管理，文字策划，数据分析，兼职，8-9k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/906',
    applyUrl: 'https://remote-china.com/jobs/906',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-111911',
    title: '外贸业务员',
    company: '天津汇来国际贸易有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '建材类产品，外贸业务员，市场拓展，客户维护，客户底盘，商务谈判，有社保，8-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/905',
    applyUrl: 'https://remote-china.com/jobs/905',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-126534',
    title: 'HR',
    company: '重庆波士科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '软件互联网行业，HR，技术/非技术岗位招聘，招聘全流程，需要大厂或者金融经验，15-27k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/904',
    applyUrl: 'https://remote-china.com/jobs/904',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-135183',
    title: '轻小说作者',
    company: '上海桌桌子信息技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '动漫动画行业，二次元相关，轻小说作者，剧本创作，男女频，9-16k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/903',
    applyUrl: 'https://remote-china.com/jobs/903',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-145454',
    title: '海外游戏策划',
    company: '奎拔科技(北京)有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '游戏行业，游戏策划，海外游戏，系统设计，关卡编辑，数据高估，Unity Editor, Prefab',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/902',
    applyUrl: 'https://remote-china.com/jobs/902',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-03332',
    title: '法律销售',
    company: '北京国舜（合肥）律师事务所',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '法律服务行业，电话销售，网络销售，案件邀约面谈，案件交接，需要行业经验，12-24k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/916',
    applyUrl: 'https://remote-china.com/jobs/916',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-1126',
    title: '研学项目协调员',
    company: '北京碧山国际旅行社有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '文旅行业，项目跟单，体验式教育项目，英语交流，团队沟通，7-8k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/915',
    applyUrl: 'https://remote-china.com/jobs/915',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-26559',
    title: '餐饮管理客服',
    company: '成都芙铭丽餐饮管理有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '餐饮管理行业，线上客服，售前/售中/售后服务，数据处理分析，6-9k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/914',
    applyUrl: 'https://remote-china.com/jobs/914',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-34508',
    title: '平面设计师',
    company: '河南友美印务有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '印刷行业，平面设计师，名片等排版设计，可日结，CDR, PS, 7-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/913',
    applyUrl: 'https://remote-china.com/jobs/913',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-4606',
    title: '职业规划师',
    company: '壹职帮(福州)数智科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '教育培训行业，职业规划师，课程销售，电话销售，有社保，7-12k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/912',
    applyUrl: 'https://remote-china.com/jobs/912',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-54362',
    title: 'AI阅读项目产品经理',
    company: '创而新(北京)科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '教育培训行业，AI阅读项目产品经理，LLM, 互联网/教育类产品经验，9-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/911',
    applyUrl: 'https://remote-china.com/jobs/911',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-62139',
    title: '全栈工程师',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: 'AI相关产品，全栈开发工程师，TypeScript, Next.js, Hono, React, L',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/910',
    applyUrl: 'https://remote-china.com/jobs/910',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-72346',
    title: '.NET方向技术总监',
    company: '远程中文网',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '国际物流行业，技术总监， .NET, C#, 团队/项目/路线图管理，战略规划，英语交流， 15-2',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/909',
    applyUrl: 'https://remote-china.com/jobs/909',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-87660',
    title: '游戏中法翻译',
    company: '甲骨易(北京)语言科技股份有限公司湖南分公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '翻译服务行业，游戏本地化，法语翻译，校对，质量测试，术语整理，10-15k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/908',
    applyUrl: 'https://remote-china.com/jobs/908',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-98603',
    title: '医学专员',
    company: '北京诺和德美医药技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '生物医药行业，医学专员，文献检查汇总，报告撰写，稿件质量控制，需要相关专业，7-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/907',
    applyUrl: 'https://remote-china.com/jobs/907',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-105676',
    title: '小红书运营',
    company: '洛阳万乾文化传媒有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '电商行业，新媒体运营，小红书店铺管理，文字策划，数据分析，兼职，8-9k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/906',
    applyUrl: 'https://remote-china.com/jobs/906',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-119508',
    title: '外贸业务员',
    company: '天津汇来国际贸易有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '建材类产品，外贸业务员，市场拓展，客户维护，客户底盘，商务谈判，有社保，8-10k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/905',
    applyUrl: 'https://remote-china.com/jobs/905',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-128691',
    title: 'HR',
    company: '重庆波士科技有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '软件互联网行业，HR，技术/非技术岗位招聘，招聘全流程，需要大厂或者金融经验，15-27k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/904',
    applyUrl: 'https://remote-china.com/jobs/904',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-131060',
    title: '轻小说作者',
    company: '上海桌桌子信息技术有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '动漫动画行业，二次元相关，轻小说作者，剧本创作，男女频，9-16k',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/903',
    applyUrl: 'https://remote-china.com/jobs/903',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
  {
    id: 'cn-remotechina-144717',
    title: '海外游戏策划',
    company: '奎拔科技(北京)有限公司',
    logo: '🌐',
    category: '远程工作',
    tags: [],
    salary: '游戏行业，游戏策划，海外游戏，系统设计，关卡编辑，数据高估，Unity Editor, Prefab',
    location: '全国远程',
    date: '2026-03-20',
    source: 'https://remote-china.com/jobs',
    sourceUrl: 'https://remote-china.com/jobs/902',
    applyUrl: 'https://remote-china.com/jobs/902',
    description: '来自远程中文网的远程工作机会',
    requirements: [],
    benefits: [],
  },
];