// ============================================================
// 国外/海外远程工作岗位数据（面向中国求职者）
// 数据来源：V2EX、电鸭、Remote OK、We Work Remotely、Arc 等
// 最后更新：2026-03-19
// ============================================================

const JOBS_GLOBAL = [
  // ── Remote OK / We Work Remotely 来源（2026年3月）────
  {
    id: "global-020",
    title: "Remote Software Engineer",
    company: "Veeam Software",
    logo: "🛡️",
    category: "后端开发",
    tags: ["Software Engineer", "Remote", "Full Time", "Enterprise"],
    salary: "$80,000-180,000/年",
    location: "全球远程",
    date: "2026-03-18",
    isNew: true,
    isFeatured: true,
    source: "https://remoteok.com/remote-dev-jobs",
    sourceUrl: "https://remoteok.com/jobs?q=software+engineer",
    currency: "USD",
    companyCountry: "美国",
    description: "Veeam Software 招聘远程软件工程师，负责企业级数据保护产品开发。",
    requirements: ["3年以上软件开发经验", "熟悉 C++/Go/Python", "英语沟通能力"],
    benefits: ["远程工作", "健康保险", "股票期权"]
  },
  {
    id: "global-021",
    title: "Senior Full-Stack Developer",
    company: "Lucid Software",
    logo: "📐",
    category: "全栈开发",
    tags: ["Full-Stack", "React", "Node.js", "Remote"],
    salary: "$100,000-150,000/年",
    location: "全球远程",
    date: "2026-03-17",
    isNew: true,
    isFeatured: true,
    source: "https://remoteok.com/remote-dev-jobs",
    sourceUrl: "https://remoteok.com/jobs?q=full-stack",
    currency: "USD",
    companyCountry: "美国",
    description: "Lucid Software 招聘高级全栈开发者，负责可视化协作平台开发。",
    requirements: ["5年以上全栈开发经验", "熟练 React + Node.js", "有 SaaS 产品经验"],
    benefits: ["远程办公", "401k 匹配", "无限假期"]
  },
  {
    id: "global-022",
    title: "DevOps Engineer",
    company: "AMK Solutions",
    logo: "☁️",
    category: "技术/运营",
    tags: ["DevOps", "AWS", "Kubernetes", "Remote"],
    salary: "$70,000-120,000/年",
    location: "全球远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remoteok.com/remote-dev-jobs",
    sourceUrl: "https://remoteok.com/jobs?q=devops",
    currency: "USD",
    companyCountry: "美国",
    description: "AMK Solutions 招聘 DevOps 工程师，负责云基础设施和自动化。",
    requirements: ["熟悉 AWS/GCP", "有 Kubernetes 经验", "CI/CD 经验"],
    benefits: ["远程工作", "技术挑战", "成长机会"]
  },
  {
    id: "global-023",
    title: "Frontend Engineer (AI Test Automation)",
    company: "mabl",
    logo: "🧪",
    category: "前端开发",
    tags: ["Frontend", "React", "AI", "Remote"],
    salary: "$90,000-140,000/年",
    location: "全球远程",
    date: "2026-03-15",
    isNew: true,
    isFeatured: false,
    source: "https://builtin.com/jobs/remote/dev-engineering",
    sourceUrl: "https://builtin.com/jobs/mabl",
    currency: "USD",
    companyCountry: "美国",
    description: "mabl 招聘前端工程师，参与 AI 驱动的测试自动化平台开发。",
    requirements: ["熟练 React", "有 AI/机器学习产品经验优先", "英语沟通"],
    benefits: ["AI 前沿", "远程办公", "健康福利"]
  },
  {
    id: "global-024",
    title: "Backend Engineer (Data Platform)",
    company: "Tech Company",
    logo: "🔧",
    category: "后端开发",
    tags: ["Backend", "Python", "Data", "Remote"],
    salary: "$80,000-130,000/年",
    location: "全球远程",
    date: "2026-03-14",
    isNew: true,
    isFeatured: false,
    source: "https://arc.dev/remote-jobs",
    sourceUrl: "https://arc.dev/remote-jobs?jobRoles=engineering",
    currency: "USD",
    companyCountry: "国际",
    description: "后端工程师，负责数据平台后端开发与优化。",
    requirements: ["熟练 Python/Go", "有数据处理经验", "英语读写"],
    benefits: ["远程工作", "弹性工时"]
  },
  {
    id: "global-025",
    title: "Product Designer (Remote-First)",
    company: "Design Agency",
    logo: "🎨",
    category: "UI/UX设计",
    tags: ["Product Design", "UI/UX", "Remote", "Full Time"],
    salary: "$60,000-100,000/年",
    location: "全球远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://dribbble.com/jobs",
    sourceUrl: "https://dribbble.com/jobs",
    currency: "USD",
    companyCountry: "国际",
    description: "远程优先的设计公司招聘产品设计师，负责 UI/UX 设计。",
    requirements: ["熟练 Figma", "有产品设计作品集", "英语沟通"],
    benefits: ["远程优先", "创意自由", "国际团队"]
  },
  // ──
  {
    id: "global-001",
    title: "数据工程师（外企 Full Remote）",
    company: "（外企·猎头代招）",
    logo: "📊",
    category: "数据分析",
    tags: ["数据工程", "Full Remote", "外企", "20-50W/年"],
    salary: "20-50W/年",
    location: "国外公司·全球远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "CNY",
    companyCountry: "外企",
    description: "外企数据工程师职位，接受国内后端工程师转岗，Full Remote 工作，薪资以年包结算，适合有3年以上后端或数据经验的工程师。",
    requirements: [
      "3年以上数据工程或后端开发经验",
      "熟悉主流数据处理工具（Spark/Flink/dbt）",
      "英语读写能力（部分英文沟通）",
      "有后端转数据经验者接受"
    ],
    benefits: ["年包结算", "Full Remote", "外企背景", "可接受后端转岗"]
  },
  {
    id: "global-002",
    title: "全栈工程师（外企·AI Agent 方向）",
    company: "（外企·40K月薪起）",
    logo: "🤖",
    category: "全栈开发",
    tags: ["全栈", "AI Agent", "外企", "Full Remote"],
    salary: "40K+/月",
    location: "国外公司·全球远程",
    date: "2026-03-15",
    isNew: true,
    isFeatured: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "CNY",
    companyCountry: "外企",
    description: "外企远程全栈工程师，专注 AI Agent 方向，月薪 40K 起，Full Remote，适合有 AI 产品研发经验的工程师。",
    requirements: [
      "3年以上全栈开发经验",
      "熟悉 AI Agent 相关技术栈（LangChain/AutoGen等）",
      "英语工作能力",
      "有 AI 产品落地经验优先"
    ],
    benefits: ["40K+月薪", "Full Remote", "外企平台", "AI 方向发展"]
  },
  {
    id: "global-003",
    title: "技术招聘官（新加坡初创·远程全职）",
    company: "新加坡初创公司",
    logo: "🇸🇬",
    category: "人力资源",
    tags: ["技术招聘", "新加坡", "远程全职", "初创"],
    salary: "面议",
    location: "新加坡·全球远程",
    date: "2026-03-14",
    isNew: true,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "SGD",
    companyCountry: "新加坡",
    description: "为新加坡初创公司招聘技术人才，远程全职工作，主要对接中国和东南亚工程师社区，建立技术招聘体系。",
    requirements: [
      "有互联网技术招聘经验",
      "熟悉工程师社区（V2EX/GitHub/领英）",
      "英语沟通能力",
      "有新加坡或东南亚市场经验优先"
    ],
    benefits: ["新加坡薪资标准", "远程全职", "初创团队"]
  },
  {
    id: "global-004",
    title: "Node.js 后端/全栈（国外项目·兼职）",
    company: "（海外团队）",
    logo: "🌿",
    category: "后端开发",
    tags: ["Node.js", "全栈", "国外项目", "兼职"],
    salary: "面议（美元结算）",
    location: "海外团队·全球远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "USD",
    companyCountry: "海外",
    description: "海外团队招聘 Node.js 后端/全栈工程师，兼职远程合作，美元结算，适合有稳定工作想赚外快的工程师。",
    requirements: [
      "熟练掌握 Node.js",
      "有全栈开发能力（React/Vue优先）",
      "基础英语沟通能力（Slack/邮件）",
      "可兼职，时间灵活"
    ],
    benefits: ["美元结算", "灵活兼职", "海外项目经验"]
  },
  {
    id: "global-005",
    title: "AI 图片工具全栈开发（国外全职）",
    company: "（海外 AI 初创）",
    logo: "🎨",
    category: "全栈开发",
    tags: ["全栈", "AI图片", "国外", "Full Remote"],
    salary: "面议（外币结算）",
    location: "海外公司·全球远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "USD",
    companyCountry: "海外",
    description: "海外 AI 初创公司招聘全栈工程师，专注 AI 图片生成工具产品研发，全职远程，外币结算。",
    requirements: [
      "熟练全栈开发（React + Python/Node.js）",
      "有 Stable Diffusion / Midjourney API 集成经验",
      "英语工作能力",
      "对 AI 图片产品有热情"
    ],
    benefits: ["外币结算", "Full Remote", "AI 方向", "初创期权"]
  },
  {
    id: "global-006",
    title: "海外软件服务项目经理",
    company: "（海外软件服务公司）",
    logo: "🌍",
    category: "产品经理",
    tags: ["项目管理", "海外", "软件服务", "10-15K/月"],
    salary: "10-15K/月",
    location: "海外公司·全球远程",
    date: "2026-03-12",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "CNY",
    companyCountry: "海外",
    description: "负责海外软件服务项目的项目管理工作，协调跨时区团队，推动项目交付，维护客户关系。",
    requirements: [
      "有软件项目管理经验（PMP证书优先）",
      "英语沟通能力（流利）",
      "熟悉跨时区协作工具（Slack/Jira/Notion）",
      "有海外客户沟通经验优先"
    ],
    benefits: ["跨国平台经验", "远程灵活", "英语提升"]
  },
  {
    id: "global-007",
    title: "前端工程师（日本 AI/Web2.5 项目·兼职）",
    company: "日本 AI 创业公司",
    logo: "🇯🇵",
    category: "前端开发",
    tags: ["前端", "日本", "AI", "Web2.5", "兼职可转全职"],
    salary: "3-6K/月（可转全职提薪）",
    location: "日本项目·全球远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "CNY",
    companyCountry: "日本",
    description: "日本 AI/Web2.5 初创项目招募前端工程师，先兼职合作3个月以上，表现优秀可转全职并调整薪资，长期合作。",
    requirements: [
      "熟练前端开发（React/Vue/TypeScript）",
      "对 AI 和 Web3 相关技术有了解",
      "基础英语沟通能力（日语为加分项）",
      "可接受兼职起步"
    ],
    benefits: ["可转全职", "日本项目经验", "长期稳定合作"]
  },
  {
    id: "global-008",
    title: "数据工程/全栈工程师（外企·Full Remote）",
    company: "（外企·猎头代招）",
    logo: "🌐",
    category: "全栈开发",
    tags: ["数据工程", "全栈", "外企", "Full Remote"],
    salary: "面议（外企标准）",
    location: "国外公司·全球远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "CNY",
    companyCountry: "外企",
    description: "外企数据工程/全栈工程师招聘，Full Remote，接受有后端或数据背景的工程师，薪资按外企标准。",
    requirements: [
      "数据工程或全栈开发经验 3 年以上",
      "熟悉数据管道或 Web 全栈技术",
      "英语工作能力",
      "有外企工作经历优先"
    ],
    benefits: ["外企薪资标准", "Full Remote", "职业背景提升"]
  },
  // ──
  {
    id: "global-009",
    title: "中国远程岗位（永久远程+股票期权）",
    company: "（神仙公司·内推通道）",
    logo: "⭐",
    category: "技术/运营",
    tags: ["永久远程", "股票期权", "国内可投", "内推"],
    salary: "面议（含股票期权）",
    location: "外资/外企·支持中国远程",
    date: "2026-03-01",
    isNew: false,
    isFeatured: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "CNY",
    companyCountry: "外企",
    description: "提供永久远程+股票期权，中国境内可直接投递，内推通道限时开放。",
    requirements: [
      "具体岗位要求以文章内容为准",
      "支持中国境内全远程工作",
      "英语工作能力（基础至流利不等）"
    ],
    benefits: ["永久远程", "股票期权", "WLB 天花板", "内推绿色通道"]
  },
  {
    id: "global-010",
    title: "远程游戏设计师（外企·赚美金）",
    company: "（外资游戏公司）",
    logo: "🎮",
    category: "UI/UX设计",
    tags: ["游戏设计", "美金薪资", "永久远程", "股票期权"],
    salary: "美金薪资+股票期权",
    location: "外资公司·全球远程",
    date: "2026-02-15",
    isNew: false,
    isFeatured: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "USD",
    companyCountry: "欧美",
    description: "外资神仙游戏公司招聘远程岗位，薪资为美金结算，永久远程工作制，提供股票期权，不用坐班、内推通道限时开放。",
    requirements: [
      "游戏设计/开发相关经验",
      "英语工作能力（流利优先）",
      "有 AAA 或独立游戏经验优先",
      "接受全远程工作模式"
    ],
    benefits: ["美金薪资", "永久远程", "股票期权", "弹性工时"]
  },
  // ──
  {
    id: "global-011",
    title: "医药相关海外销售",
    company: "江西中洪博元生物技术有限公司",
    logo: "💊",
    category: "市场营销",
    tags: ["海外销售", "医药", "英语口语", "B端客户"],
    salary: "20-35K/月",
    location: "全国远程（服务海外市场）",
    date: "2026-03-09",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    currency: "CNY",
    companyCountry: "中国（服务海外）",
    description: "负责动物实验耗材/试剂向海外 B 端药企客户的销售工作，需具备英语口语交流能力，面向欧美市场。",
    requirements: [
      "英语口语流利",
      "有 B 端医药/生命科学销售经验",
      "了解欧美医药/科研采购流程",
      "自驱力强，适应远程工作"
    ],
    benefits: ["高提成", "远程自由", "海外市场经验积累"]
  },
  {
    id: "global-012",
    title: "CRM 项目经理（粤语/台语优先）",
    company: "纬致科技（北京）有限公司",
    logo: "📋",
    category: "产品经理",
    tags: ["CRM", "项目管理", "粤语", "英语交流"],
    salary: "16-23K/月",
    location: "全国远程（服务港澳台/国际客户）",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/849",
    sourceUrl: "https://remote-china.com/jobs/849",
    currency: "CNY",
    companyCountry: "中国（服务港澳台）",
    description: "负责 CRM 平台的营销活动管理与客户审核项目，服务港澳台及国际客户，需要英语交流能力，粤语/台语优先。",
    requirements: [
      "CRM 项目管理经验",
      "英语交流能力",
      "粤语或台语（优先）",
      "有港澳台或外资项目经验优先"
    ],
    benefits: ["涉外项目背景", "弹性远程", "绩效奖金"]
  },
  {
    id: "global-013",
    title: "跨境电商产品运营（可兼职）",
    company: "（跨境 SaaS 产品）",
    logo: "🛍️",
    category: "运营",
    tags: ["跨境电商", "SaaS", "产品运营", "可兼职"],
    salary: "面议",
    location: "全国远程（跨境业务）",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/872",
    sourceUrl: "https://remote-china.com/jobs/872",
    currency: "CNY",
    companyCountry: "中国（跨境业务）",
    description: "负责跨境电商 SaaS 产品的运营工作，涵盖供应链一件代发、用户行为数据分析和品牌社区管理，可兼职。",
    requirements: [
      "有跨境电商运营经验（Amazon/Shopify等）",
      "数据分析能力（用户行为）",
      "社区管理经验",
      "可兼职"
    ],
    benefits: ["可兼职", "跨境业务经验", "灵活远程"]
  },
  {
    id: "global-014",
    title: "英语游戏本地化 PM",
    company: "新宇智慧",
    logo: "🎯",
    category: "产品经理",
    tags: ["游戏本地化", "英语", "项目管理", "翻译"],
    salary: "10-18K/月",
    location: "全国远程",
    date: "2026-03-12",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/889",
    sourceUrl: "https://remote-china.com/jobs/889",
    currency: "CNY",
    companyCountry: "中国（服务海外游戏）",
    description: "负责英语游戏本地化项目管理，包括流程把控、风险管理及多方协调，服务国际游戏客户。",
    requirements: [
      "有游戏本地化或翻译项目管理经验",
      "英语交流能力（流利）",
      "项目管理经验（PMP优先）",
      "了解游戏行业优先"
    ],
    benefits: ["游戏行业背景", "英语提升", "远程灵活"]
  },
  {
    id: "global-015",
    title: "生成式广告素材专家（全球 ToC）",
    company: "（全球 AI 广告公司）",
    logo: "🌟",
    category: "市场营销",
    tags: ["AIGC", "广告素材", "全球ToC", "全职远程"],
    salary: "面议",
    location: "全球远程",
    date: "2026-03-15",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/871",
    sourceUrl: "https://remote-china.com/jobs/871",
    currency: "CNY",
    companyCountry: "国际",
    description: "负责使用 AI 生成面向全球消费者市场的广告素材，优化广告投放策略，覆盖多个国际市场。",
    requirements: [
      "有 AIGC 工具（MidJourney/Sora/Adobe Firefly）使用经验",
      "有国际市场广告投放或素材制作经验",
      "英语工作能力",
      "数据驱动的优化思维"
    ],
    benefits: ["全球业务视野", "AI 工具前沿", "远程全职"]
  }
];
