// ============================================================
// 国内远程工作岗位数据
// 数据来源：V2EX、电鸭、远程中文网等
// 最后更新：2026-03-19
// 标记 canRefer: true 的职位表示可内推（来自 V2EX、电鸭社群）
// ============================================================

const JOBS_CN = [
  // ── V2EX 来源（可内推）────
  {
    id: "cn-030",
    title: "Blockchain Engineer (Node.js / Blockchain)",
    company: "（外企远距招聘）",
    logo: "⛓️",
    category: "后端开发",
    tags: ["Blockchain", "Node.js", "Web3", "外企", "Remote"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-18",
    isNew: true,
    isFeatured: true,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1199376",
    description: "外企远距招聘 Blockchain 工程师，负责区块链技术研发，可在家工作。",
    requirements: ["熟悉 Node.js 区块链开发", "有智能合约开发经验", "英语读写能力"],
    benefits: ["外企氛围", "Full Remote", "弹性工时"]
  },
  {
    id: "cn-031",
    title: "AI 负责人（Head of AI / Head of Applied AI）",
    company: "（Web3 华人团队）",
    logo: "🤖",
    category: "AI/算法",
    tags: ["AI", "Head of AI", "Web3", "远程全职"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-17",
    isNew: true,
    isFeatured: true,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1198943",
    description: "Web3 华人团队招聘 AI 负责人，负责 AI 战略规划与技术团队管理。",
    requirements: ["深厚的 AI 背景", "团队管理经验", "对 Web3 有兴趣"],
    benefits: ["核心团队", "远程办公", "Token 激励"]
  },
  {
    id: "cn-032",
    title: "智能合约工程师/区块链工程师",
    company: "（DV Labs）",
    logo: "🔗",
    category: "后端开发",
    tags: ["智能合约", "区块链", "Solidity", "Remote"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-17",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1198928",
    description: "DV Labs 招聘智能合约工程师，参与区块链项目开发。",
    requirements: ["熟悉 Solidity", "有智能合约部署经验", "了解 EVM"],
    benefits: ["远程全职", "项目分成"]
  },
  {
    id: "cn-033",
    title: "前端开发（北美 AI 公司·Junior-Mid）",
    company: "（北美 AI 公司）",
    logo: "🇺🇸",
    category: "前端开发",
    tags: ["前端", "React", "北美", "AI", "Remote"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1199120",
    description: "北美 AI 公司自己团队招聘 Junior-Mid 级别前端开发，国内 Remote。",
    requirements: ["熟练掌握 React", "有 AI 产品开发经验优先", "英语沟通能力"],
    benefits: ["北美团队", "Remote", "AI 赛道"]
  },
  {
    id: "cn-034",
    title: "外企招聘数据工程师（20-50W/年）",
    company: "（外企·猎头代招）",
    logo: "📊",
    category: "数据分析",
    tags: ["数据工程", "Full Remote", "外企", "20-50W/年"],
    salary: "20-50W/年",
    location: "全国远程",
    date: "2026-03-15",
    isNew: true,
    isFeatured: true,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1198745",
    description: "外企数据工程师职位，接受国内后端工程师转岗，Full Remote 工作，薪资以年包结算。",
    requirements: ["3年以上数据工程或后端开发经验", "熟悉主流数据处理工具（Spark/Flink/dbt）", "英语读写能力"],
    benefits: ["年包结算", "Full Remote", "外企背景", "可接受后端转岗"]
  },
  {
    id: "cn-035",
    title: "生成式广告素材专家/资深广告策略优化师",
    company: "（AI 生产全球 TOC 行业）",
    logo: "📢",
    category: "市场营销",
    tags: ["AI", "广告", "全职远程", "TOC"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-15",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1198659",
    description: "AI 生产全球 TOC 行业招聘生成式广告素材专家，全职远程，负责广告策略优化。",
    requirements: ["有广告投放经验", "熟悉 AI 生成工具", "数据分析能力"],
    benefits: ["全职远程", "AI 行业", "绩效奖金"]
  },
  {
    id: "cn-036",
    title: "远程全栈工程师（外企·AI Agent 方向）",
    company: "（外企·40K月薪起）",
    logo: "⚡",
    category: "全栈开发",
    tags: ["全栈", "AI Agent", "外企", "Full Remote", "40K+"],
    salary: "40K+/月",
    location: "全国远程",
    date: "2026-03-14",
    isNew: true,
    isFeatured: true,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1196808",
    description: "外企远程全栈工程师，专注 AI Agent 方向，月薪 40K 起，Full Remote。",
    requirements: ["3年以上全栈开发经验", "熟悉 AI Agent 相关技术栈（LangChain/AutoGen等）", "英语工作能力"],
    benefits: ["40K+月薪", "Full Remote", "外企平台", "AI 方向发展"]
  },
  {
    id: "cn-037",
    title: "AI 应用工程师",
    company: "（AI 初创）",
    logo: "🧠",
    category: "后端开发",
    tags: ["AI", "应用开发", "Remote"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-14",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1195183",
    description: "远程 AI 应用工程师，负责 AI 产品研发与落地。",
    requirements: ["熟悉主流 AI 框架", "有 AI 产品开发经验", "自驱力强"],
    benefits: ["AI 赛道", "远程办公", "成长空间"]
  },
  {
    id: "cn-038",
    title: "远程办公内推 - Java/Go/前端/iOS/安卓",
    company: "（大厂待遇）",
    logo: "🏢",
    category: "后端开发",
    tags: ["Java", "Go", "前端", "iOS", "安卓", "大厂"],
    salary: "大厂待遇",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1195285",
    description: "年后第一波最新 HC，Java，Go，前端，iOS，安卓等，大厂待遇，可远程办公。",
    requirements: ["有对应语言开发经验", "有互联网大厂背景优先", "内推通道"],
    benefits: ["大厂待遇", "远程办公", "内推"]
  },
  {
    id: "cn-039",
    title: "AI 产品工程师（Python + LLM API）",
    company: "（北京初创）",
    logo: "🤖",
    category: "后端开发",
    tags: ["Python", "LLM API", "AI", "北京/远程"],
    salary: "10-15K/月",
    location: "北京/全国远程",
    date: "2026-03-12",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1196103",
    description: "参与 AI 产品研发，使用 Python 和 LLM API 构建智能应用功能模块。",
    requirements: ["熟练使用 Python", "有 LLM API 集成经验", "对 AI 产品有热情"],
    benefits: ["弹性工时", "初创氛围", "成长空间"]
  },
  {
    id: "cn-040",
    title: "Crypto 交易所远程岗位（Android/iOS/量化开发）",
    company: "（Crypto 交易所）",
    logo: "💰",
    category: "后端开发",
    tags: ["Crypto", "Android", "iOS", "量化", "远程"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-12",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1196521",
    description: "Crypto 交易所招聘 Android、iOS、量化开发等远程岗位。",
    requirements: ["有移动端或量化开发经验", "了解 Crypto 行业", "可远程协作"],
    benefits: ["Crypto 行业", "远程办公", "高成长"]
  },
  {
    id: "cn-041",
    title: "Python 工程师（AI/RAG 方向）",
    company: "（AI 初创）",
    logo: "🐍",
    category: "后端开发",
    tags: ["Python", "AI", "RAG", "远程全职"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-11",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1194013",
    description: "招聘 Python 工程师，AI/RAG 方向，负责智能应用后端开发。",
    requirements: ["熟练使用 Python", "有 RAG 框架经验", "熟悉 LLM API 集成"],
    benefits: ["AI 方向", "远程全职", "成长空间"]
  },
  {
    id: "cn-042",
    title: "Node.js 远程后端程序员",
    company: "（海外项目）",
    logo: "🟢",
    category: "后端开发",
    tags: ["Node.js", "后端", "Remote"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-11",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://www.v2ex.com/t/1192721",
    description: "海外项目招聘 Node.js 远程后端程序员，可兼职或全职。",
    requirements: ["熟练掌握 Node.js", "有后端项目经验", "可远程协作"],
    benefits: ["海外项目", "远程办公"]
  },
  // ── 电鸭来源（可内推）────
  {
    id: "cn-050",
    title: "远程招聘前端/后端工程师",
    company: "（电鸭社区）",
    logo: "🦆",
    category: "全栈开发",
    tags: ["前端", "后端", "远程", "可全职", "可兼职"],
    salary: "20k-40k",
    location: "全国远程",
    date: "2026-03-18",
    isNew: true,
    isFeatured: true,
    canRefer: true,
    source: "https://eleduck.com/",
    sourceUrl: "https://eleduck.com/posts/ZXfAWg",
    description: "远程招聘前端/后端工程师，可全职可兼职，薪资 20k-40k。",
    requirements: ["熟练前端或后端开发", "有项目经验", "可远程协作"],
    benefits: ["可全职/兼职", "薪资 20k-40k", "远程办公"]
  },
  {
    id: "cn-051",
    title: "AI 公司招全栈工程师（React/Node.js）",
    company: "（AI 公司）",
    logo: "🤖",
    category: "全栈开发",
    tags: ["全栈", "React", "Node.js", "AI", "远程全职"],
    salary: "22k-40k/月",
    location: "全国远程",
    date: "2026-03-17",
    isNew: true,
    isFeatured: true,
    canRefer: true,
    source: "https://eleduck.com/",
    sourceUrl: "https://eleduck.com/posts/R3faq7",
    description: "AI 公司招聘全栈工程师，负责 AI 平台开发，要求 React + Node.js 技术栈。",
    requirements: ["熟练 React + Node.js", "有 AI 产品开发经验", "自驱力强"],
    benefits: ["薪资 22k-40k/月", "AI 赛道", "远程全职"]
  },
  {
    id: "cn-052",
    title: "快速开发团队招前端偏全栈开发",
    company: "（快速原型验证团队）",
    logo: "🚀",
    category: "全栈开发",
    tags: ["前端", "全栈", "远程", "利润分成"],
    salary: "10K-18K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://eleduck.com/",
    sourceUrl: "https://eleduck.com/posts/v5f8Wk",
    description: "快速原型验证团队招聘前端偏全栈开发，远程办公，表现优秀可参与利润分成。",
    requirements: ["熟练前端开发", "有全栈能力优先", "速度快"],
    benefits: ["10K-18K/月", "利润分成", "远程办公"]
  },
  {
    id: "cn-053",
    title: "全栈开发工程师（偏前端/AI模型应用）",
    company: "（AI 创业团队）",
    logo: "💡",
    category: "全栈开发",
    tags: ["全栈", "前端", "AI", "Fully Remote"],
    salary: "30-40K/月",
    location: "全国远程",
    date: "2026-03-15",
    isNew: true,
    isFeatured: true,
    canRefer: true,
    source: "https://eleduck.com/",
    sourceUrl: "https://eleduck.com/posts/QZfdN0",
    description: "全职远程/Fully Remote，招聘全栈开发工程师（偏前端），AI模型应用方向。",
    requirements: ["熟练 React/TypeScript/Next.js", "有大厂经验优先", "AI 模型应用经验"],
    benefits: ["30-40K/月", "Fully Remote", "AI 方向"]
  },
  {
    id: "cn-054",
    title: "AI 项目全栈/前端工程师",
    company: "（AI 创业项目）",
    logo: "🧪",
    category: "前端开发",
    tags: ["AI", "全栈", "前端", "远程全职"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-14",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://eleduck.com/",
    sourceUrl: "https://eleduck.com/posts/b2fWKl",
    description: "AI 创业项目招聘全栈/前端工程师，参与文生视频方向 AI 产品开发。",
    requirements: ["熟悉前端或全栈开发", "对 AI 有热情", "可远程协作"],
    benefits: ["AI 创业", "远程办公", "成长空间"]
  },
  {
    id: "cn-055",
    title: "招全栈工程师（Java 后端 + Vue 前端）",
    company: "（远程团队）",
    logo: "☕",
    category: "全栈开发",
    tags: ["Java", "Vue", "若依框架", "全远程"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://eleduck.com/",
    sourceUrl: "https://eleduck.com/posts/gYfLBv",
    description: "招全栈程序员 Java 后端，熟悉若依框架，前端 Vue，全远程工作。",
    requirements: ["熟练 Java 若依框架", "熟悉 Vue", "全栈开发经验"],
    benefits: ["全远程", "项目稳定"]
  },
  {
    id: "cn-056",
    title: "招聘全栈或 Java 后端工程师",
    company: "（医药行业 SAAS）",
    logo: "💊",
    category: "后端开发",
    tags: ["Java", "Angular", "全栈", "远程全职"],
    salary: "14-16K/月",
    location: "全国远程",
    date: "2026-03-12",
    isNew: true,
    isFeatured: false,
    canRefer: true,
    source: "https://eleduck.com/",
    sourceUrl: "https://eleduck.com/posts/DjfdAz",
    description: "医药行业 SAAS 产品项目，招聘全栈偏后端或纯后端工程师。",
    requirements: ["3年以上 Java 开发经验", "有 Angular 经验优先", "英语读写能力"],
    benefits: ["14-16K/月", "行业稳定", "远程全职"]
  },
    title: "AI 产品工程师",
    company: "（北京初创）",
    logo: "🤖",
    category: "后端开发",
    tags: ["Python", "LLM API", "AI", "北京/远程"],
    salary: "10-15K/月",
    location: "北京/全国远程",
    date: "2026-03-15",
    isNew: true,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "参与 AI 产品研发，使用 Python 和 LLM API 构建智能应用功能模块，与小团队紧密协作。",
    requirements: ["熟练使用 Python", "有 LLM API（OpenAI/Claude/Gemini）集成经验", "对 AI 产品有热情"],
    benefits: ["弹性工时", "初创氛围", "成长空间"]
  },
  {
    id: "cn-021",
    title: "前端工程师（AI 音乐视频平台）",
    company: "（AI 创业公司）",
    logo: "🎵",
    category: "前端开发",
    tags: ["前端", "AI", "音乐", "视频"],
    salary: "15-20K/月",
    location: "全国远程",
    date: "2026-03-14",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责 AI 音乐视频平台的前端研发，打造创意交互体验，与设计师和后端紧密协作。",
    requirements: ["熟练掌握主流前端框架（React/Vue）", "有音视频类产品开发经验优先", "关注用户体验"],
    benefits: ["远程全职", "AI 赛道", "创业期权"]
  },
  {
    id: "cn-022",
    title: "全栈工程师（兼职/AI驱动）",
    company: "（AI 工具初创）",
    logo: "⚡",
    category: "全栈开发",
    tags: ["全栈", "AI", "兼职", "灵活"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-12",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "参与 AI 驱动工具产品的全栈开发，灵活远程合作，技术栈不限，重视实际产出能力。",
    requirements: ["全栈开发能力（前后端均可）", "有 AI 工具产品开发经验优先", "可兼职，自驱力强"],
    benefits: ["灵活兼职", "项目分成机会"]
  },
  {
    id: "cn-023",
    title: "杭州/远程 全栈工程师（偏前端）",
    company: "（杭州科技公司）",
    logo: "🌊",
    category: "前端开发",
    tags: ["全栈", "前端", "React", "杭州/远程"],
    salary: "面议",
    location: "杭州/全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责公司核心产品前端研发，偏向全栈方向，可选择杭州办公或全程远程。",
    requirements: ["熟练使用 React 或 Vue", "有 Node.js 基础", "有独立产品开发经验优先"],
    benefits: ["杭州/远程二选一", "弹性工时"]
  },
  {
    id: "cn-024",
    title: "Web3 运营（长期）",
    company: "（Web3 项目方）",
    logo: "⛓️",
    category: "运营",
    tags: ["Web3", "社区运营", "长期", "远程"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: false,
    source: "https://www.v2ex.com/go/remote",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责 Web3 项目的社区运营与增长工作，维护国内外社区渠道，推动用户增长。",
    requirements: ["对 Web3/区块链有深入了解", "有 Telegram/Discord 社区运营经验", "可接受 Token 部分薪资"],
    benefits: ["Token 激励", "远程自由", "长期合作"]
  },
  // ── 2026-03-16 ──
  {
    id: "cn-001",
    title: "物流技术运营专员",
    company: "艾吉赛国际物流集团",
    logo: "🚚",
    category: "运营",
    tags: ["MySQL", "Python", "夜班协作", "远程全职"],
    salary: "8-10K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/894",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责跨时区夜班协作，系统维护及数据库维护工作，支持国际物流集团日常运营。",
    requirements: ["熟悉 MySQL、Python", "可接受跨时区夜班工作", "有物流/运营相关经验优先"],
    benefits: ["五险一金"]
  },
  {
    id: "cn-002",
    title: "HR主管",
    company: "（代招·电商行业）",
    logo: "👥",
    category: "人力资源",
    tags: ["HR", "电商", "远程全职"],
    salary: "20-21K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/893",
    sourceUrl: "https://www.zhipin.com/job_detail/b188f87a8320fc2703dz2ti1GVdS.html",
    description: "负责电商公司组织人事全流程，包括员工培训实施、员工关系管理等工作。",
    requirements: ["HR全流程经验", "有电商行业背景优先", "组织培训能力强"],
    benefits: ["绩效奖金"]
  },
  {
    id: "cn-003",
    title: "插画设计师",
    company: "海宁米晗文化传播有限公司",
    logo: "🎨",
    category: "UI/UX设计",
    tags: ["插画", "兼职", "电商设计"],
    salary: "8-12K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/892",
    sourceUrl: "https://www.zhaopin.com/jobdetail/CCL1475319280J40833117707.htm",
    description: "承接电商设计/宣传海报/出版物/包装等插画创作，线上接单，可兼职合作。",
    requirements: ["有插画设计作品集", "熟悉电商视觉规范", "可接受按稿计费"],
    benefits: ["灵活兼职", "作品积累"]
  },
  {
    id: "cn-004",
    title: "商旅客服",
    company: "外企德科",
    logo: "✈️",
    category: "客户服务",
    tags: ["差旅服务", "客服", "远程全职"],
    salary: "8-12K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/891",
    sourceUrl: "#",
    description: "为企业客户提供差旅全流程支持，对接酒店、机票、用车等预订，整理知识库与SOP。",
    requirements: ["有客服/差旅服务经验", "沟通能力强", "有社保"],
    benefits: ["五险一金", "大外企背景"]
  },
  {
    id: "cn-005",
    title: "新媒体运营",
    company: "（留学服务行业）",
    logo: "📱",
    category: "运营",
    tags: ["新媒体", "文案", "留学"],
    salary: "7-8K/月",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/887",
    sourceUrl: "#",
    description: "负责留学服务机构的新媒体内容创作与账号日常运营，包括文案整理、视频剪辑、社群搭建和客户咨询工作。",
    requirements: ["英语读写能力", "有新媒体运营经验", "了解留学行业优先"],
    benefits: ["弹性工时"]
  },
  // ── 2026-03-13 ──
  {
    id: "cn-006",
    title: "GOLANG 后端开发",
    company: "（猎头代招）",
    logo: "⚙️",
    category: "后端开发",
    tags: ["Golang", "微服务", "Kubernetes", "远程全职"],
    salary: "20-40K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: true,
    source: "https://remote-china.com/jobs/884",
    sourceUrl: "https://www.zhipin.com/job_detail/2f8614091104659e0nVz29q_GVNV.html",
    description: "负责可观测平台后端研发，数据采集分析，参与微服务架构设计与优化。",
    requirements: ["Golang 扎实", "熟悉微服务架构", "有 Kubernetes 使用经验", "可观测平台经验优先"],
    benefits: ["猎头推荐", "大厂待遇"]
  },
  {
    id: "cn-007",
    title: "广告投放项目经理",
    company: "珠海翼进顾问咨询有限公司",
    logo: "📊",
    category: "运营",
    tags: ["广告投放", "项目管理", "远程全职"],
    salary: "15-20K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/883",
    sourceUrl: "#",
    description: "负责广告投放项目统筹管理，数据跟进复盘，策略执行优化，覆盖多媒体渠道。",
    requirements: ["有广告投放或项目管理经验", "数据分析能力强", "逻辑思维清晰"],
    benefits: ["绩效奖金", "弹性远程"]
  },
  {
    id: "cn-008",
    title: "招聘专员",
    company: "武汉银禾科技有限公司",
    logo: "🔍",
    category: "人力资源",
    tags: ["招聘", "软件互联网", "远程全职"],
    salary: "14-28K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/882",
    sourceUrl: "https://www.zhipin.com/job_detail/fa94f3e6ad411ddf0nZ42929F1FX.html",
    description: "全流程招聘执行，渠道优化，数据分析，支持软件互联网行业人才获取。",
    requirements: ["有互联网行业招聘经验", "熟悉主流招聘平台", "数据驱动的招聘思维"],
    benefits: ["五险一金", "绩效提成"]
  },
  {
    id: "cn-009",
    title: "思辨老师",
    company: "杭州维学新知网络科技有限公司",
    logo: "📚",
    category: "教育/培训",
    tags: ["小班教学", "小学生", "远程全职"],
    salary: "8-12K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/885",
    sourceUrl: "#",
    description: "面向小学生开展思辨逻辑小班在线教学，培养学生批判思维和表达能力。",
    requirements: ["有小学段教学经验", "表达能力强", "耐心细致"],
    benefits: ["五险（大连参保）", "课时奖励"]
  },
  {
    id: "cn-010",
    title: "线上行政客服",
    company: "济南云旅商贸服务有限公司",
    logo: "💬",
    category: "客户服务",
    tags: ["客服", "电商", "兼职可"],
    salary: "6-8K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/886",
    sourceUrl: "#",
    description: "解答公司产品问题，跟踪客户需求，维护良好客户关系，可全职或兼职。",
    requirements: ["沟通能力强", "打字速度 50+ 字/分钟", "有电商平台经验优先"],
    benefits: ["灵活兼职", "提成奖励"]
  },
  // ── 2026-03-11 ──
  {
    id: "cn-011",
    title: "JAVA 高级架构师",
    company: "上海游昆信息技术有限公司",
    logo: "☕",
    category: "后端开发",
    tags: ["Java", "分布式系统", "广告技术", "远程全职"],
    salary: "30-50K/月",
    location: "全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: true,
    source: "https://remote-china.com/jobs/880",
    sourceUrl: "#",
    description: "负责大数据平台产品的高级架构设计，参与广告技术生态建设，推动分布式系统技术升级。",
    requirements: ["精通 Java 和分布式系统", "熟悉广告技术生态", "有大型平台架构设计经验"],
    benefits: ["高薪", "股票期权", "弹性远程"]
  },
  {
    id: "cn-012",
    title: "全栈工程师（AI Agent）",
    company: "中硅星云科技（广州）有限公司",
    logo: "🤖",
    category: "全栈开发",
    tags: ["Node.js", "Python", "Flutter", "AI Agent", "RAG"],
    salary: "12-24K/月",
    location: "全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/876",
    sourceUrl: "https://www.zhaopin.com/jobdetail/CCL1507259470J40831719411.htm",
    description: "参与 AI Agent 相关产品研发，独立完成前后端功能模块开发，覆盖移动端与 Web。",
    requirements: ["熟练使用 Node.js / Python / Golang", "有 Flutter 开发经验", "了解 RAG 框架优先"],
    benefits: ["弹性工时", "AI 方向成长"]
  },
  {
    id: "cn-013",
    title: "GO 开发工程师",
    company: "深圳漫奢生物科技有限公司",
    logo: "🐹",
    category: "后端开发",
    tags: ["Golang", "Java", "云原生", "To B SaaS"],
    salary: "17-20K/月",
    location: "全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/875",
    sourceUrl: "#",
    description: "外贸行业 To B SaaS 产品后端开发，负责云原生架构迭代与 DevOps 流程建设。",
    requirements: ["熟练掌握 Golang/Java", "了解 DevOps 和云原生技术", "有 To B SaaS 开发经验优先"],
    benefits: ["弹性远程", "绩效奖金"]
  },
  {
    id: "cn-014",
    title: "知识产权专员（英语笔译）",
    company: "北京安杰世泽律师事务所",
    logo: "⚖️",
    category: "法律/知识产权",
    tags: ["知识产权", "英语翻译", "专利", "远程全职"],
    salary: "13-15K/月",
    location: "全国远程",
    date: "2026-03-11",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/874",
    sourceUrl: "https://www.zhaopin.com/jobdetail/CCL1436870760J40757721506.htm",
    description: "处理知识产权相关事务及英语笔译工作，服务于知名律师事务所的涉外知产业务。",
    requirements: ["化学工程/高分子材料相关专业", "持有专利代理师资格证", "英语笔译能力强"],
    benefits: ["专业背景积累", "大所平台"]
  },
  // ── 2026-03-10 ──
  {
    id: "cn-015",
    title: "全栈工程师（AI Ads Agent）",
    company: "（广告营销行业初创）",
    logo: "💡",
    category: "全栈开发",
    tags: ["Python", "Node.js", "React", "LLM API", "RAG"],
    salary: "20-30K/月",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: true,
    source: "https://remote-china.com/jobs/866",
    sourceUrl: "https://eleduck.com/posts/dDfgvD",
    description: "负责 AI 广告 Agent 产品全栈研发，接入 LLM API 和 RAG 框架，打造智能广告生成工具。",
    requirements: ["熟悉 Python、Node.js、React", "有 LLM API 接入经验", "了解 RAG 框架优先"],
    benefits: ["初创期权", "AI 赛道机会"]
  },
  {
    id: "cn-016",
    title: ".NET 全栈开发（兼职）",
    company: "WooPOS",
    logo: "🛒",
    category: "全栈开发",
    tags: [".NET", "Blazor", "GraphQL", "兼职", "ERP"],
    salary: "50-120元/小时",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/865",
    sourceUrl: "#",
    description: "参与进销存 ERP 系统开发，使用 .NET、Blazor、GraphQL 技术栈，灵活兼职合作。",
    requirements: ["熟练掌握 .NET / Blazor", "了解 GraphQL", "有 ERP 系统开发经验优先"],
    benefits: ["时薪结算", "灵活兼职"]
  },
  {
    id: "cn-017",
    title: "Python 后端开发",
    company: "大连思泰克科技有限公司",
    logo: "🐍",
    category: "后端开发",
    tags: ["Python", "FastAPI", "TypeScript", "英语交流"],
    salary: "14-28K/月",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/864",
    sourceUrl: "#",
    description: "负责软件外包项目的后端开发工作，使用 Python FastAPI，具备基本前端能力，支持英语交流。",
    requirements: ["熟练掌握 Python、FastAPI", "基本前端能力（TypeScript）", "英语交流能力"],
    benefits: ["远程弹性", "外包项目奖金"]
  },
  // ── 2026-03-09 ──
  {
    id: "cn-018",
    title: "谷歌 SEO 专员",
    company: "成都柳暗星河科技有限公司",
    logo: "🔎",
    category: "市场营销",
    tags: ["SEO", "Google", "外链建设", "数据分析"],
    salary: "10-20K/月",
    location: "全国远程",
    date: "2026-03-09",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/856",
    sourceUrl: "#",
    description: "负责谷歌 SEO 优化工作，包括关键词优化、SEO 审计、外链建设及数据分析报告。",
    requirements: ["有 Google SEO 实战经验", "熟悉 SEO 工具（Ahrefs/SEMrush）", "数据分析能力"],
    benefits: ["弹性远程", "绩效提成"]
  },
  {
    id: "cn-019",
    title: "前端/后端工程师",
    company: "（软件外包）",
    logo: "💻",
    category: "前端开发",
    tags: ["Vue", "Java", "Spring", "兼职可"],
    salary: "20-40K/月",
    location: "全国远程",
    date: "2026-03-09",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/854",
    sourceUrl: "#",
    description: "参与软件外包项目开发，前端使用 Vue，后端使用 Java+Spring，可兼职合作。",
    requirements: ["前端：熟练掌握 Vue", "后端：熟练掌握 Java、Spring", "可兼职"],
    benefits: ["可兼职", "灵活合作"]
  },
  // ── remote-china.com 新增职位（2026年3月）────
  {
    id: "cn-057",
    title: "英至越南语笔译",
    company: "（翻译服务）",
    logo: "🌐",
    category: "翻译",
    tags: ["笔译", "越南语", "兼职", "远程"],
    salary: "6-10K/月",
    location: "全国远程",
    date: "2026-03-12",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/895",
    sourceUrl: "https://remote-china.com/jobs/895",
    description: "翻译服务行业，英语至越南语笔译，长期兼职合作。",
    requirements: ["英语至越南语翻译能力", "有翻译经验优先", "可长期合作"],
    benefits: ["兼职", "灵活结算"]
  },
  {
    id: "cn-058",
    title: "独立律师",
    company: "湖北赤云律师事务所",
    logo: "⚖️",
    category: "法律",
    tags: ["律师", "独立律师", "案件承办", "远程"],
    salary: "8-15K/月",
    location: "全国远程",
    date: "2026-03-12",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/895",
    sourceUrl: "https://remote-china.com/jobs/895",
    description: "法律服务行业，独立律师，案件承办，客户维护，参与律所会议，需要执业证书。",
    requirements: ["律师执业证书", "案件承办经验", "客户维护能力"],
    benefits: ["独立执业", "灵活工作"]
  },
  {
    id: "cn-059",
    title: "医学专员",
    company: "世联博研(北京)科技有限公司",
    logo: "💊",
    category: "医疗健康",
    tags: ["医学专员", "文献检查", "报告撰写", "远程全职"],
    salary: "7-10K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/907",
    sourceUrl: "https://remote-china.com/jobs/907",
    description: "生物医药行业，医学专员，文献检查汇总，报告撰写，稿件质量控制，需要相关专业背景。",
    requirements: ["医学/生物相关专业", "文献检查能力", "报告撰写经验"],
    benefits: ["专业背景", "远程全职"]
  },
  {
    id: "cn-060",
    title: "生物学数据标注",
    company: "深圳市法本信息技术股份有限公司",
    logo: "🧬",
    category: "数据标注",
    tags: ["数据标注", "生物学", "兼职", "时薪"],
    salary: "时薪 200-300元",
    location: "全国远程",
    date: "2026-03-07",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/895",
    sourceUrl: "https://remote-china.com/jobs/895",
    description: "软件外包行业，大模型数据标注，生活学相关内容，含竞赛内容，需要相关专业背景，英文读写能力。",
    requirements: ["生物学相关专业背景", "英文读写能力", "细心认真"],
    benefits: ["时薪结算", "兼职灵活"]
  },
  {
    id: "cn-061",
    title: "全栈开发工程师",
    company: "Team247",
    logo: "💻",
    category: "全栈开发",
    tags: ["全栈", "远程", "英语交流"],
    salary: "15-30K/月",
    location: "全国远程",
    date: "2026-03-12",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/895",
    sourceUrl: "https://remote-china.com/jobs/895",
    description: "软件外包行业，全栈开发工程师，要求英语交流能力。",
    requirements: ["全栈开发经验", "英语交流能力", "可远程协作"],
    benefits: ["远程办公", "外语环境"]
  },
  {
    id: "cn-062",
    title: "Java后端开发（兼职）",
    company: "SmartDeer",
    logo: "☕",
    category: "后端开发",
    tags: ["Java", "后端", "兼职", "财务系统"],
    salary: "12-20K/月",
    location: "全国远程",
    date: "2026-03-06",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/895",
    sourceUrl: "https://remote-china.com/jobs/895",
    description: "人力资源行业，后端开发工程师，财务系统，Java, Spring Boot，兼职合作。",
    requirements: ["熟练 Java/Spring Boot", "有财务系统经验优先", "可兼职"],
    benefits: ["兼职", "项目稳定"]
  },
  {
    id: "cn-063",
    title: "美工视频剪辑师",
    company: "（健康咨询行业）",
    logo: "🎬",
    category: "设计",
    tags: ["美工", "视频剪辑", "兼职", "上海"],
    salary: "6-8K/月",
    location: "全国远程",
    date: "2026-03-14",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/896",
    sourceUrl: "https://remote-china.com/jobs/896",
    description: "健康咨询行业，美工/视频剪辑师，宣传物料设计，视频剪辑后期，base上海优先。",
    requirements: ["视频剪辑能力", "宣传物料设计经验", "Base上海优先"],
    benefits: ["创意工作", "远程办公"]
  },
  {
    id: "cn-064",
    title: "课程运营/社群运营",
    company: "（教育培训）",
    logo: "📚",
    category: "运营",
    tags: ["课程运营", "社群运营", "Python", "数据分析"],
    salary: "9-13K/月",
    location: "全国远程",
    date: "2026-03-14",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/897",
    sourceUrl: "https://remote-china.com/jobs/897",
    description: "教育培训行业，课程运营，社群管理，Python编程课程，私域活动策划，数据分析，需要有开发相关背景。",
    requirements: ["课程运营经验", "社群管理能力", "数据分析能力", "有开发背景优先"],
    benefits: ["成长空间", "远程办公"]
  },
  {
    id: "cn-065",
    title: "线上校长",
    company: "杭州博文知行文化艺术有限公司",
    logo: "🏫",
    category: "教育/培训",
    tags: ["线上校长", "教务管理", "远程全职"],
    salary: "20-30K/月",
    location: "全国远程",
    date: "2026-03-17",
    isNew: true,
    isFeatured: true,
    source: "https://remote-china.com/jobs/897",
    sourceUrl: "https://remote-china.com/jobs/897",
    description: "教育培训行业，线上校长，教学教务管理，建立家校沟通机制，培训经验，需要有校长经验。",
    requirements: ["校长经验", "教学教务管理能力", "家校沟通经验"],
    benefits: ["高薪", "远程全职"]
  },
  {
    id: "cn-066",
    title: "软件架构师（兼职）",
    company: "猿圈圈智能技术(南京)有限公司",
    logo: "🏗️",
    category: "后端开发",
    tags: ["架构师", "Java", "Go", "Python", "兼职"],
    salary: "15-20K/月",
    location: "全国远程",
    date: "2026-03-12",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/897",
    sourceUrl: "https://remote-china.com/jobs/897",
    description: "AI相关产品，软件架构师，Java/Go/Python，DDD，架构设计，边界控制，团队搭建，兼职合作。",
    requirements: ["深厚架构设计经验", "熟悉 DDD", "团队管理能力"],
    benefits: ["兼职", "AI方向"]
  },
  {
    id: "cn-067",
    title: "后端开发工程师",
    company: "VANZO Media",
    logo: "🔧",
    category: "后端开发",
    tags: ["后端", "Python", "Node.js", "AI", "远程全职"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-12",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/897",
    sourceUrl: "https://remote-china.com/jobs/897",
    description: "广告营销行业，AI KOL 营销产品，后端开发工程师，Python/Node.js/TypeScript，LangChain/LangGraph，数据工程，性能优化，女性友好。",
    requirements: ["熟练 Python/Node.js", "了解 LangChain", "有 AI 产品经验优先"],
    benefits: ["AI赛道", "远程全职"]
  },
  {
    id: "cn-068",
    title: "小红书运营（兼职）",
    company: "（电商行业）",
    logo: "📕",
    category: "运营",
    tags: ["小红书", "运营", "兼职", "数据分析"],
    salary: "8-9K/月",
    location: "全国远程",
    date: "2026-03-17",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/906",
    sourceUrl: "https://remote-china.com/jobs/906",
    description: "电商行业，新媒体运营，小红书店铺管理，文字策划，数据分析，兼职合作。",
    requirements: ["小红书运营经验", "文案策划能力", "数据分析能力"],
    benefits: ["兼职", "热门平台"]
  },
  {
    id: "cn-069",
    title: "运营负责人",
    company: "拍活",
    logo: "📊",
    category: "运营",
    tags: ["运营负责人", "新媒体", "社群", "远程全职"],
    salary: "面议",
    location: "全国远程",
    date: "2026-03-16",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/906",
    sourceUrl: "https://remote-china.com/jobs/906",
    description: "软件外包行业，新媒体运营，社群运营，连接企业需求方和自由职业者。",
    requirements: ["运营管理经验", "社群运营能力", "资源对接能力"],
    benefits: ["核心岗位", "远程办公"]
  },
  {
    id: "cn-070",
    title: "医学设备销售",
    company: "世联博研(北京)科技有限公司",
    logo: "💰",
    category: "销售",
    tags: ["销售", "医学设备", "生物医药", "远程全职"],
    salary: "15-30K/月",
    location: "全国远程",
    date: "2026-03-13",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/907",
    sourceUrl: "https://remote-china.com/jobs/907",
    description: "生物医药行业，生命科学食品销售，大型食品学术宣讲经验优先，进口产品中文资料整理。",
    requirements: ["销售经验", "医学/生物背景优先", "学术宣讲能力"],
    benefits: ["高提成", "远程办公"]
  },
  {
    id: "cn-071",
    title: "职业药师",
    company: "吉林省东晟泰大药房有限公司",
    logo: "💊",
    category: "医疗健康",
    tags: ["药师", "医药零售", "远程全职"],
    salary: "8-12K/月",
    location: "全国远程",
    date: "2026-01-26",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/907",
    sourceUrl: "https://remote-china.com/jobs/907",
    description: "医药零售行业，职业药师，中西医不限，年龄不限，需要执业药师资格证。",
    requirements: ["执业药师资格证", "医药零售经验"],
    benefits: ["行业稳定", "远程办公"]
  },
  {
    id: "cn-072",
    title: "生命科学销售",
    company: "默普生物科技(山东)有限公司",
    logo: "🔬",
    category: "销售",
    tags: ["销售", "生命科学", "远程全职", "江苏"],
    salary: "9-15K/月",
    location: "江苏区域远程",
    date: "2026-01-23",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/907",
    sourceUrl: "https://remote-china.com/jobs/907",
    description: "生物医药行业，销售工程师，生命科学相关，客户开发，市场调研，生物学相关专业背景，江苏区域远程。",
    requirements: ["生物学相关专业背景", "销售经验", "客户开发能力"],
    benefits: ["区域远程", "专业背景"]
  },
  {
    id: "cn-073",
    title: "海外游戏策划",
    company: "奎拔科技(北京)有限公司",
    logo: "🎮",
    category: "游戏",
    tags: ["游戏策划", "海外游戏", "远程全职"],
    salary: "8-15K/月",
    location: "全国远程",
    date: "2026-03-18",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/907",
    sourceUrl: "https://remote-china.com/jobs/907",
    description: "游戏行业，游戏策划，海外游戏，系统设计，关卡编辑，数据高估，Unity Editor，益智类游戏。",
    requirements: ["游戏策划经验", "Unity Editor 使用经验", "海外游戏了解"],
    benefits: ["游戏行业", "远程办公"]
  },
  {
    id: "cn-074",
    title: "游戏中法翻译",
    company: "（翻译服务）",
    logo: "🎮",
    category: "翻译",
    tags: ["游戏翻译", "法语", "本地化", "兼职"],
    salary: "10-15K/月",
    location: "全国远程",
    date: "2026-03-18",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/908",
    sourceUrl: "https://remote-china.com/jobs/908",
    description: "翻译服务行业，游戏本地化，法语翻译，校对，质量测试，术语整理。",
    requirements: ["法语翻译能力", "游戏本地化经验", "校对能力"],
    benefits: ["游戏行业", "远程兼职"]
  },
  {
    id: "cn-075",
    title: "中日游戏兼职翻译",
    company: "创思佳业",
    logo: "🎮",
    category: "翻译",
    tags: ["游戏翻译", "日语", "兼职", "远程"],
    salary: "9-18K/月",
    location: "全国远程",
    date: "2026-03-18",
    isNew: true,
    isFeatured: false,
    source: "https://remote-china.com/jobs/908",
    sourceUrl: "https://remote-china.com/jobs/908",
    description: "翻译服务行业，游戏翻译，日语，游戏文本翻译，术语管理，质量交付，兼职合作。",
    requirements: ["日语翻译能力", "游戏文本翻译经验", "术语管理能力"],
    benefits: ["兼职", "游戏行业"]
  },
  {
    id: "cn-076",
    title: "日语专利翻译（兼职）",
    company: "创博翻译(北京)有限公司",
    logo: "📝",
    category: "翻译",
    tags: ["翻译", "日语", "专利", "兼职"],
    salary: "7-10K/月",
    location: "全国远程",
    date: "2026-03-10",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/908",
    sourceUrl: "https://remote-china.com/jobs/908",
    description: "翻译服务行业，日语翻译，简中到日语翻译，技术或医药翻译经验，有保密协议。",
    requirements: ["日语翻译能力", "技术/医药翻译经验", "保密意识"],
    benefits: ["兼职", "专业翻译"]
  },
  {
    id: "cn-077",
    title: "中英游戏翻译",
    company: "新宇智慧",
    logo: "🎮",
    category: "翻译",
    tags: ["游戏翻译", "英语", "本地化", "远程"],
    salary: "8-14K/月",
    location: "全国远程",
    date: "2026-03-05",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/908",
    sourceUrl: "https://remote-china.com/jobs/908",
    description: "翻译服务行业，游戏本地化翻译，英语翻译较验，质量管理。",
    requirements: ["英语翻译能力", "游戏本地化经验", "质量管理能力"],
    benefits: ["游戏行业", "远程办公"]
  },
  {
    id: "cn-078",
    title: "跨境电商运营专员",
    company: "外企德科",
    logo: "🛒",
    category: "运营",
    tags: ["跨境电商", "运营", "英语", "远程全职"],
    salary: "10-15K/月",
    location: "全国远程",
    date: "2026-02-05",
    isNew: false,
    isFeatured: false,
    source: "https://remote-china.com/jobs/894",
    sourceUrl: "https://remote-china.com/jobs/894",
    description: "代招，跨境电商行业，电商运营专员，物流对接，商家拓展，客服指导，英语交流，有社保，跨时区工作。",
    requirements: ["跨境电商运营经验", "英语交流能力", "物流对接经验"],
    benefits: ["有社保", "跨时区工作"]
  }
];
